### ISSUE TITLE
un supported operation on getRow

### ISSUE THREAD

**Issue by mqasimnawaz** [monitorjbl/excel-streaming-reader#116]
I understand there are many methods that are not supported using this api. can you explain to me the reason that why  getRow( num)  method is not supported ? also this is a feature request as well if possible.

**Comment by monitorjbl** [comment]
It's not supported because this library is a streaming API. You can't seek to arbitrary positions in the sheet, you have to iterate through everything as it comes in. The purpose of this library is to minimize memory consumption so you can load huge sheets. Random access would require the sheet to be loaded into memory, which is what vanilla POI does.

I'm going to close this issue as getRow is unsupportable, but if you have more questions feel free to ask.

**Comment by mqasimnawaz** [comment]
thanks for the explanation, and yes that is what I am currently doing to skip n number of rows to get to a specific row i assumed that it would be possible to jump to specific row without loading file into memory or just load a specific part of file into memory i.e. specific 5k rows etc. for my case vanilla POI fails even if file size is around 10 mb it takes like 15 minutes to load file into memory. This streaming api reduced that time to around 3-5 seconds depends on file size, the max i have reached is i guess 10 seconds which is alot better than vanilla POI. anyways thumbs up for this

**Comment by monitorjbl** [comment]
Yeah, it's understandable that you might think that. It might be slightly faster if native support for skipping ahead was added, but we have to process the XML stream up to that point anyway. Underneath this library is just a SAX parser, so there's no way to have it skip to the Nth occurrence of an element.
