### ISSUE TITLE
Way to identify which sheets are hidden which are not hidden

### ISSUE THREAD

**Issue by Izzathulla** [monitorjbl/excel-streaming-reader#26]
Hi

Could you provide a way to identify the type of excel sheet (Hidden sheet or not)

Thanks,
Izzath

**Comment by Izzathulla** [comment]
I fixed it on StreamingReader.java...

**Comment by monitorjbl** [comment]
Currently, this is not going to be possible just due to the way the API works. You select a sheet either by name or by index, you don't get an object that can be inspected. However, I've been working on an updated API so you can stream multiple sheets simultaneously. It's in the [0.3 branch](https://github.com/monitorjbl/excel-streaming-reader/tree/0.3), and it should be possible to do so there.
