### ISSUE TITLE
Way of get a RowCount before Iterating over Rows

### ISSUE THREAD

**Issue by nardhar** [monitorjbl/excel-streaming-reader#28]
Is it possible? because the only way i know to get an iterator count is to iterate over all items, maybe what could be done is getting the last <row> and read its "r" attr, but don't know how to do it. Any suggestions are welcome.

Thx

**Comment by monitorjbl** [comment]
Yes, you'd have to read the entire stream to get the count. The caveat of streaming the data is that you cannot randomly access items.

**Comment by nardhar** [comment]
in a file with xlsx extension and saved from excel 2010 there seems to be a <dimension> tag at the beggining, and apparently it saves the range of the whole area of the sheet, getting the last row would be trivial from its "ref" attribute, of course it shouldn't be trusted but at least it would be an estimate, I'll investigate more on how to read the <dimension> tag in a fast way
Please let me know if this approach is good or not
Thx

**Comment by monitorjbl** [comment]
Hmm, that's a good question. I hadn't heard of that tag before, but if it's accurate then I would definitely see if it's possible to pull in.

**Comment by monitorjbl** [comment]
@nardhar It doesn't look like this can be used. The range isn't indicative of the number of rows that are contained within it. Rather, it only sets an upper bound on the *maximum* number of rows that can be in the sheet. If the range is `A1:G10`, that doesn't mean that there are 10 rows in the sheet because blank rows are not present in the XML and are not iterated over. There will be at most 10 rows, but without reading the entire document you can't know how many there actually were.

I'm going to close this issue as it doesn't appear to be possible to implement this in a streaming fashion. If you come across anything in the future that contains this data, let me know!
