### ISSUE TITLE
Possibility to disable Shared Strings Table

### ISSUE THREAD

**Issue by andersjaensson** [monitorjbl/excel-streaming-reader#35]
The entire shared strings table is read into memory, which can have a very big impact on memory consumtion. Would it be possible to add an option to use inline strings instead?
See https://poi.apache.org/apidocs/org/apache/poi/xssf/streaming/SXSSFWorkbook.html for some background.

**Comment by bitdivine** [comment]
When writing, sure, a writer can write inline strings instead of creating a string table.  However when reading it looks as if the file already contains a strings table so the reader has no choice but to deal with it.  That doesn't mean that it cannot use less memory when using the strings table, e.g. with multi-pass (fast) or storing the table on disk (slower but simpler).
