### ISSUE TITLE
Show blank cell

### ISSUE THREAD

**Issue by samuelfac** [monitorjbl/excel-streaming-reader#77]
When cell is blank at the excel, the code ignore this and pass to next cell, but I need the blank cells. How I can show blanks cell??

```
for (Row r : reader) {
    for (Cell c : r) {
        //... show blank cell here.
    }
}
```

Version:0.2.13

**Comment by monitorjbl** [comment]
That's a pretty old version of this library, but I believe the behavior will be the same in the latest version. This should match what POI does natively, if the cell/row does not actually exist at the coordinate specified, it does not return anything. In this library's case, the reason for that is because the data literally does not exist; the XML document that describes the sheet only contains cells that have values. 

There aren't many reasons that one would want to iterate over blank values as its just an inefficient waste of time in most cases. However, if you do the [row number](https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Row.html#method_summary) and [column numbers](https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Cell.html#method_summary) are available, so the best approach is to just check the cell's coordinate and fill in any gaps from the last cell.

**Comment by samuelfac** [comment]
OK.

I used **column numbers** to control this situation.

Thank you.
